### ISSUE TITLE
StartUp issue enabling on 1.13

### ISSUE THREAD

**Issue by SoraShiunin** [Indyuce/bounty-hunters#1]
Bounty Hunters 2.2
Minecraft: 1.13.2
Error: https://pastebin.com/LjfaQ7Re

**Comment by Indyuce** [comment]
Latest versions use player UUIDs to store data. The plugin is trying to get an UUID from a player name (player names were previously used to store data) which is impossible ; so you will have to back up & delete your /BountyHunters plugin folder.
This is probably better than replacing everything since a lot of things have changed in the configs since, and removing the plugin folder will generate the most recent versions of the config files.
