### ISSUE TITLE
Features request for bounty removing

### ISSUE THREAD

**Issue by JohOply** [Indyuce/bounty-hunters#11]
Hi there

I have some ideas to improve the behaviour of the bounty removing :)

- Add a permission to be able to remove own bounty (currently, there is no permission, the only condition is to have set the bounty)
- Add a tax when player remove his bounty (a new one)
- ~~Add a command or option to admin to be able to remove bounty added by someone else~~

When there is more than 1 player who set a bounty:
- Add an option to prevent a player from removing the bounty he had set
- Add an option to allow a player to remove the bounty he had set on a specific player, instead of removing all bounties set on this target

Please tell me what do you think about :)

Anyway, thank you for your work!
Cheers

**Comment by Indyuce** [comment]
Sounds nice, not sure when I can get that implemented. Admins **can** remove player bounties using /bounties remove <target>

**Comment by JohOply** [comment]
Ah nice! I didn't see it! It works fine! Could you add the /boutines remove command in the main page (or in the wiki)?

**Comment by Indyuce** [comment]
Updated the wiki

**Comment by Indyuce** [comment]
Currently working on improving how bounties are handled. Right now if the original owner removes his bounty, everything is cancelled and I see a lot of potential glitches.

- if we don't apply a tax on extra player bounty contributions, then the og creator that use his alt to create a bounty, put a low base reward and increase it indefinitely using his main, and he will be able to escape that base tax
- if we however apply a tax on extra contributions, og creator can just remove the bounty without others wanting and therefore can make anyone lose money bc of the taxes. Then he can do that repeatedly with his main to prevent other players from placing big bounties on his head.

That system needs to be removed because of how unsafe it is. From now on, if the og bounty creator removes his bounty, some other contributor will be chosen to be the "bounty creator" and therefore the bounty will not entirelly expire.
A bounty may only expire if all the contributors removed their contribution + if there are no extra reward due to the auto bounty for example. I think this is a much better system

Edit 3: I'm also adding a permission to let players remove their contribution to a bounty and probably an admin GUI to edit a bounty (edit the extra auto-bounty reward and player's contributions). Ticket will be closed as soon as the update is out later today
