### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Creator cannot be null

### ISSUE THREAD

**Issue by SladeHazard** [Indyuce/bounty-hunters#31]
Please fix: https://hastebin.com/nomarejadi.cs I'm using the plugin deluxecombat which runs a console command to set bounty on a player when he reaches 5 kills streak The author said the error is from your plugin!

Okay so the error is coming because the console is setting the bounty why was this removed in bounty hunters premium and works fine in legacy? PLZ FIX! i want this feature back!!

**Comment by Indyuce** [comment]
It works fine in Legacy because the API is not structured the same way. Tell DeluxeCombat developper to use `Bounty(OfflinePlayer target, double reward)` instead of `Bounty(OfflinePlayer creator, OfflinePlayer target, double reward)` because the constructor with the creator as first argument makes a null check. The issue is not on BountyHunters end, this type of java error simply indicates the API is not used the right way
