### ISSUE TITLE
Unable to use /bounty or /bounties BUG.

### ISSUE THREAD

**Issue by BboyZeroOne** [Indyuce/bounty-hunters#51]
Players are unable to use the command /bounty, /bounties or any commands although they have the required permission.

This is what they see when they use the command.
![unknown9](https://user-images.githubusercontent.com/51330952/87420985-d42d5480-c608-11ea-925d-0a580742ca25.png)

This issue could be related to #50 

Running Paper 1.15.2 on Plugin version 2.2.6.

**Comment by Indyuce** [comment]
That must be an issue with BH Legacy tho this plugin is not getting updates anymore

**Comment by BboyZeroOne** [comment]
I'm using BH Premium though

**Comment by Indyuce** [comment]
Keep in mind you should only report issues if you're using the very latest version of the plugin. Latest version of BH Premium is 2.3.9

**Comment by BboyZeroOne** [comment]
Okay, let me get it updated! And I will let you know!

**Comment by BboyZeroOne** [comment]
This issue still exist in the premium version! 2.3.10

It will show the message for non OP.

**Comment by Indyuce** [comment]
Have you tried running BountyHunters on a fresh server setup or/and using a different permission plugin?

**Comment by BboyZeroOne** [comment]
Nope, but I believe it was running bountyhunters since the beginning of the server. Permission plugin kept the same... Luckperms.

**Comment by Indyuce** [comment]
I just tried deoping myself with LuckPerms, couldn't run /bounties. As soon as I used `lp user Indyuce permission set bountyhunters.list true`, I instantly got access back to /bounties. I have already tried adding support for Vault perms tho that would cause issues because some plugins don't like calling perm checks on the main thread which is what BH does. You should give a fresh server setup a try
