### ISSUE TITLE
Compass broken on the 2.3.10

### ISSUE THREAD

**Issue by dryter97** [Indyuce/bounty-hunters#53]
i can totaly say its the 2.3.10 but the version isnt change when you compile so..... yea the 2.3.9 is show instead.

the compass isnt working properly in first place and in second place we got this issus about the compass himself in the console

[https://paste.pandacrafts.ca/zejakadeyo.sql](https://paste.pandacrafts.ca/zejakadeyo.sql)

**Comment by Indyuce** [comment]
I'm not sure these logs are related to the compass issue. There's indeed a bug when comparing bed spawn point locations if the two spawn points are in different worlds which I'll fix asap.
Also 2.3.10 does indicate 2.3.9 which should be a problem with the update checker, that will be fixed in the next build.
I would need more information about how the compass does not work and how to replicate that issue
