### ISSUE TITLE
Internal error when use /hunter command

### ISSUE THREAD

**Issue by tylerking** [Indyuce/bounty-hunters#67]
When you using the /hunter command this message is shown:

"An internal error occurred while attempting to perform this command

and this is the console error: https://pastebin.com/We1Abgmv

Any ideas on whats going on?

**Comment by Indyuce** [comment]
https://github.com/Indyuce/bounty-hunters/issues/56

**Comment by Indyuce** [comment]
It looks like a very common issue yet I literally have NO idea how to replicate it. I've tried several times already to start a server and try and mess with the leaderboard but I just can't find what's wrong. It might be a plugin loading issue but no one provided startup logs

Edit: it was an issue concerning the leaderboard GUI trying to access offline player data, should be fixed in 2.3.13

**Comment by Indyuce** [comment]
Should be fixed now.
