### ISSUE TITLE
trigger bounty w/ api based on killer player & killed uuid

### ISSUE THREAD

**Issue by hafarooki** [Indyuce/bounty-hunters#68]
I have a custom plugin for combat log NPCs. How do I make it trigger bounty claiming for offline players with the API?

**Comment by Indyuce** [comment]
See https://github.com/Indyuce/bounty-hunters/blob/master/src/net/Indyuce/bountyhunters/listener/BountyClaim.java

I suppose your NPCs are not player entities as otherwise it should trigger the PlayerDeathEvent and BH should hook onto that. You can copy and paste the code of the BountyClaim class and replace PlayerDeathEvent by EntityDeathEvent while checking if your entity is the right player's NPC.

Some methods might not be supported because they require a Player instance, by removing some of the on-bounty-claim functionalities it should adapt well to an NPC death event
