### ISSUE TITLE
I want to translate plugin in Russian but can't

### ISSUE THREAD

**Issue by Wylabb** [Indyuce/bounty-hunters#78]
Plugin just clears everything in lang file after I finish translation

**Comment by Indyuce** [comment]
I've tried editing the items language file and it seems to load fine after I hit /reload. That might be caused by special symbols glitching the config file.
What you can do is slowly edit your config, adding one special char at a time to see which one would be causing that issue. If adding a simple character still causes the issue, then it's probably on BH end.

You can also upload one of your config files which reset every time you reload your server so I can give it a try on my end.

**Comment by Indyuce** [comment]
Closed till more info is provided

**Comment by Wylabb** [comment]
try to insert russian symbols to language file and it will clear everything, for example "п", "р", "ц" etc
